'use client';
import { useEffect, useState, useCallback } from 'react';
import { Newspaper, ArrowUpRight, ArrowRight, Bookmark, SlidersHorizontal, Sparkles, RefreshCw, Plus, Check, Globe2, ChevronRight, LogOut, LayoutGrid, List, LoaderCircle, Info } from 'lucide-react';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Checkbox } from '@/components/ui/checkbox';
import { Empty, EmptyHeader, EmptyTitle, EmptyDescription } from '@/components/ui/empty';
import { Toaster, toast } from 'sonner';
import { publishers, type Article, type DeskState, type Topic } from '@/lib/publishers';
import { useDeskTools } from './use-desk-tools';
const blank:DeskState = {selected:[],articles:[],scraps:[],topics:[],statuses:[],analysisMode:'none',analysisAt:null,aiAvailable:false};
const responseData=async(r:Response)=>await r.json() as DeskState & {error?:string;warning?:string};
const views = [{id:'front',label:'온라인 1면'},{id:'opinion',label:'사설 · 오피니언'},{id:'ranking',label:'이슈 랭킹'},{id:'scraps',label:'내 스크랩'}];
export default function Desk({user,signInUrl,signOutUrl}:{user:{name:string;email:string}|null;signInUrl:string;signOutUrl:string}) {
 const [state,setState]=useState<DeskState>(blank), [view,setView]=useState('front'), [settings,setSettings]=useState(false), [draft,setDraft]=useState<string[]>([]), [loading,setLoading]=useState(!!user), [busy,setBusy]=useState(false), [error,setError]=useState(''), [filter,setFilter]=useState('all'), [layout,setLayout]=useState('grid'), [topic,setTopic]=useState<Topic|null>(null), [method,setMethod]=useState(false), [savingIds,setSavingIds]=useState<string[]>([]), [date,setDate]=useState('');
 const load=useCallback(async()=>{if(!user)return;try{const r=await fetch('/api/desk');const d=await responseData(r);if(!r.ok)throw Error(d.error);setState(d);setError('');}catch(e){setError(e instanceof Error?e.message:'뉴스 데스크를 불러오지 못했습니다.');}finally{setLoading(false)}},[user]);
 useEffect(()=>{load();setDate(new Intl.DateTimeFormat('ko-KR',{year:'numeric',month:'long',day:'numeric',weekday:'long',timeZone:'Asia/Seoul'}).format(new Date()));},[load]);
 useEffect(()=>{if(!user||!state.selected.length)return;const timer=setInterval(()=>load(),300000);return()=>clearInterval(timer)},[user,state.selected.length,load]);
 const openSettings=()=>{setDraft(state.selected);setSettings(true)};
 async function saveSettings(){setBusy(true);try{const r=await fetch('/api/settings',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({publishers:draft})});const d=await responseData(r);if(!r.ok)throw Error(d.error);setState(s=>({...s,selected:draft,articles:s.articles.filter(a=>draft.includes(a.publisher)),topics:[]}));setFilter('all');setSettings(false);toast.success('언론사 설정을 저장했습니다.');if(draft.length)await refresh();else await load();}catch(e){toast.error(e instanceof Error?e.message:'저장하지 못했습니다.')}finally{setBusy(false)}}
 async function refresh(){setBusy(true);try{const r=await fetch('/api/refresh',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});const d=await responseData(r);if(!r.ok)throw Error(d.error);await load();if(d.warning)toast(d.warning);else toast.success('뉴스 데스크를 업데이트했습니다.')}catch(e){toast.error(e instanceof Error?e.message:'업데이트하지 못했습니다.')}finally{setBusy(false)}}
 async function scrap(a:Article){if(!user)return;const saved=state.scraps.some(s=>s.id===a.id);setSavingIds(v=>[...v,a.id]);try{const r=await fetch('/api/scraps',{method:saved?'DELETE':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({articleId:a.id})});const d=await responseData(r);if(!r.ok)throw Error(d.error);setState(s=>({...s,scraps:saved?s.scraps.filter(x=>x.id!==a.id):[a,...s.scraps]}));toast.success(saved?'스크랩을 해제했습니다.':'내 스크랩에 저장했습니다.')}catch(e){toast.error(e instanceof Error?e.message:'스크랩하지 못했습니다.')}finally{setSavingIds(v=>v.filter(id=>id!==a.id))}}
 useDeskTools(setView);
 const available=state.selected.map(id=>publishers.find(p=>p.id===id)!).filter(Boolean);
 const articles=(view==='scraps'?state.scraps:state.articles.filter(a=>a.section===view)).filter(a=>filter==='all'||a.publisher===filter);
 const breaking=state.articles.find(a=>/\[속보\]|^속보/.test(a.title));
 const ready=!!user&&state.selected.length>0;
 function ArticleCard({a,index=0}:{a:Article;index?:number}){const p=publishers.find(p=>p.id===a.publisher)!;const saved=state.scraps.some(x=>x.id===a.id);return <article className={'article-card '+(index===0&&view==='front'?'lead-article':'')}><div className="article-source"><span style={{color:p.color}}>{p.name}</span><span>{a.section==='opinion'?'오피니언':'온라인 1면'}</span></div><a href={`/article/${a.id}`} className="article-link"><h3>{a.title}</h3><ArrowUpRight size={20}/></a><div className="article-bottom"><span>{a.publishedAt?new Date(a.publishedAt).toLocaleString('ko-KR',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit',timeZone:'Asia/Seoul'}):'원문 발행 시각 미제공'}</span><button className={'icon-button '+(saved?'saved':'')} onClick={()=>scrap(a)} disabled={savingIds.includes(a.id)} aria-label={saved?'스크랩 해제':'기사 스크랩'}><Bookmark size={18} fill={saved?'currentColor':'none'}/></button></div></article>}
 return <div className="site-shell"><Toaster position="bottom-right" richColors/>
 <header className="masthead"><div className="masthead-inner"><a href="/" className="brand" aria-label="PRESSROOM 홈">PRESS<span>ROOM</span><i/></a><div className="brand-divider"/><span className="brand-caption">뉴스를 한눈에</span><div className="header-right"><span className="edition">오늘의 뉴스 <Globe2 size={14}/></span>{user?<><span className="account-name">{user.name.split('@')[0]} 님</span><a className="logout" href={signOutUrl} target="_top" aria-label="로그아웃"><LogOut size={17}/></a></>:<a className="signin" href={signInUrl} target="_top">로그인 <ArrowUpRight size={16}/></a>}</div></div></header>
 <div className="navigation"><nav aria-label="주요 메뉴"><Tabs value={view} onValueChange={v=>{setView(v);setFilter('all')}}><TabsList className="main-tabs">{views.map(v=><TabsTrigger className="main-tab" value={v.id} key={v.id}>{v.id==='ranking'&&<Sparkles size={15}/>} {v.label}{v.id==='scraps'&&state.scraps.length>0&&<span className="tab-count">{state.scraps.length}</span>}</TabsTrigger>)}</TabsList></Tabs><button className="settings-nav" onClick={openSettings}><SlidersHorizontal size={16}/> 언론사 설정</button></nav></div>
 <div className="ticker"><div className="ticker-inner"><span className="breaking-label"><span className="live-dot"/> 속보</span>{breaking?<a href={`/article/${breaking.id}`}>{breaking.title} <ArrowUpRight size={15}/></a>:<span className="ticker-text">{ready?'새로운 속보가 들어오면 이곳에서 확인할 수 있습니다.':'세상의 소식을, 나만의 뉴스 데스크에서 만나보세요.'}</span>}<span className="ticker-end">실시간 업데이트</span></div></div>
 <main className="desk-wrap"><section className="page-heading"><div><div className="eyebrow">MY NEWS</div><h1>{view==='front'?'나의 뉴스 데스크':view==='opinion'?'사설 · 오피니언':view==='ranking'?'오늘의 공통 이슈':'내 스크랩'}<span className="heading-dot">.</span></h1><p>{view==='front'?'여러 언론사의 첫 시선을 한곳에서 읽어보세요.':view==='opinion'?'같은 세상을 바라보는 서로 다른 관점을 만나보세요.':view==='ranking'?'여러 언론사가 함께 주목하는 이야기를 확인하세요.':'다시 읽고 싶은 기사를 편하게 모아두세요.'}</p></div><div className="heading-meta"><span>{date}</span><span className="meta-caption">{state.analysisAt?'마지막 분석 '+new Date(state.analysisAt).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit',timeZone:'Asia/Seoul'}):'나만의 데일리 브리핑'}</span></div></section>
 <div className="publisher-strip"><div className="strip-label">MY PRESS <span>{state.selected.length.toString().padStart(2,'0')}</span></div><div className="press-pills">{available.length?available.map(p=><button key={p.id} className={'press-pill '+(filter===p.id?'active':'')} onClick={()=>setFilter(filter===p.id?'all':p.id)}><span style={{background:p.color}}/>{p.name}</button>):<span className="no-press">아직 선택한 언론사가 없습니다.</span>}</div><button className="add-publishers" onClick={openSettings}><Plus size={16}/><span>언론사 선택</span></button></div>
 <div className="desk-columns"><section className="main-column"><div className="section-heading"><h2>{view==='front'?'오늘의 1면':view==='opinion'?'오늘의 오피니언':view==='ranking'?'공통 보도 순위':'저장한 기사'} <span>{view==='ranking'?state.topics.length:articles.length}</span></h2><div className="section-actions">{ready&&<button onClick={refresh} disabled={busy} className="refresh"><RefreshCw size={15} className={busy?'spin':''}/><span>{busy?'수집 중':'새로고침'}</span></button>}{view!=='ranking'&&<div className="view-switch"><button onClick={()=>setLayout('grid')} aria-label="격자 보기" aria-pressed={layout==='grid'} className={layout==='grid'?'active':''}><LayoutGrid size={16}/></button><button onClick={()=>setLayout('list')} aria-label="목록 보기" aria-pressed={layout==='list'} className={layout==='list'?'active':''}><List size={17}/></button></div>}</div></div>
 {error&&<div role="alert" className="error-banner">{error}<button onClick={load}>다시 시도</button></div>}
 {ready&&state.statuses.some(s=>s.status!=='ok')&&<p role="status" className="selection-note">일부 언론사의 수집이 지연되었습니다. 아래 수집 상태에서 확인할 수 있습니다.</p>}
 {ready&&state.analysisMode==='keyword'&&<p className="selection-note">현재 제목 유사도 분석을 표시합니다. GPT 분석은 아직 적용되지 않았습니다.</p>}
 {loading?<div className="loading-state"><LoaderCircle className="spin"/> 뉴스 데스크를 불러오는 중입니다.</div>:(!ready&&view!=='scraps')?<div className="onboarding"><Empty className="onboard-empty"><EmptyHeader><div className="paper-illustration" aria-hidden="true"><div className="paper-back"/><div className="paper-front"><div className="paper-logo">PRESSROOM<span/></div><div className="paper-rule"/><div className="paper-layout"><div className="paper-square"/><div className="paper-lines"><i/><i/><i/></div></div><div className="paper-lines wide"><i/><i/></div></div><span className="paper-plus"><Plus size={22}/></span></div><div className="onboard-kicker">A FRESH START</div><EmptyTitle className="empty-title">당신의 첫 번째 뉴스 데스크</EmptyTitle><EmptyDescription className="empty-copy">관심 있는 언론사를 선택해 주세요.<br/>온라인 1면부터 사설까지, 나에게 필요한 뉴스만 모아드릴게요.</EmptyDescription></EmptyHeader>{user?<button className="primary-button" onClick={openSettings}>언론사 선택하기 <ArrowRight size={17}/></button>:<a className="primary-button" href={signInUrl} target="_top">로그인하고 시작하기 <ArrowRight size={17}/></a>}<span className="onboard-note">{user?'언론사 설정은 언제든지 변경할 수 있어요.':'로그인하면 언론사 설정과 스크랩이 저장됩니다.'}</span></Empty><div className="start-steps"><div><span>01</span><strong>로그인</strong><small>나만의 데스크 만들기</small></div><ChevronRight size={15}/><div><span>02</span><strong>언론사 선택</strong><small>다양한 시선 모으기</small></div><ChevronRight size={15}/><div><span>03</span><strong>읽고, 스크랩</strong><small>나의 관점 넓히기</small></div></div></div>:view==='ranking'?<div className="ranking-list">{state.topics.length?state.topics.map((t,i)=><button className="ranking-card" key={t.title} onClick={()=>setTopic(t)}><span className="rank-no">{String(i+1).padStart(2,'0')}</span><div><h3>{t.title}</h3><p>{t.summary}</p><small>{t.publisherCount}개 언론사 · {t.articleIds.length}개 기사</small></div><ArrowUpRight size={20}/></button>):<div className="plain-empty"><Sparkles/><h3>함께 주목한 이슈를 찾고 있습니다.</h3><p>2개 이상 언론사의 공통 보도가 수집되면 순위가 나타납니다.</p></div>}</div>:articles.length?<div className={'articles '+layout}>{articles.map((a,i)=><ArticleCard key={a.id} a={a} index={i}/>)}</div>:<div className="plain-empty">{view==='scraps'?<Bookmark/>:<Newspaper/>}<h3>{view==='scraps'?'아직 스크랩한 기사가 없습니다.':busy?'선택한 언론사의 뉴스를 모으고 있습니다.':'표시할 기사가 없습니다.'}</h3><p>{view==='scraps'?'기사의 북마크 버튼을 눌러 여기에 모아보세요.':'새로고침하거나 아래 언론사 수집 상태를 확인해 주세요.'}</p></div>}
 {ready&&state.statuses.length>0&&view!=='scraps'&&<details className="source-health"><summary>언론사 수집 상태 <span>{state.statuses.filter(s=>s.status==='ok').length}/{state.statuses.length} 정상</span></summary>{state.statuses.map(s=><div key={s.publisher+s.section}><span>{publishers.find(p=>p.id===s.publisher)?.name} · {s.section==='front'?'1면':'오피니언'}</span><span>{s.status==='ok'?s.count+'개 수집':s.message||'연결 확인 필요'}</span></div>)}</details>}
 <div className="press-directory"><div className="section-heading compact"><h2>다양한 시선, 더 넓은 세상</h2><button onClick={openSettings}>전체 언론사 <ArrowUpRight size={14}/></button></div><p>종합일간지부터 경제지까지, {publishers.length}개 언론사를 한곳에서.</p><div className="publisher-logos">{publishers.map(p=><button key={p.id} onClick={openSettings} style={{color:p.color}}>{p.name}</button>)}</div></div>
 </section><aside className="side-column"><section className="issue-panel"><div className="issue-title"><h2><Sparkles size={18}/> 이슈 랭킹</h2><span className="ai-badge">{state.analysisMode==='gpt'?'GPT':'TOPICS'}</span></div><p className="side-description">언론사가 함께 주목한 오늘의 뉴스</p>{state.topics.length?state.topics.slice(0,5).map((t,i)=><button className="side-topic" key={t.title} onClick={()=>setTopic(t)}><b>{i+1}</b><div><h3>{t.title}</h3><span>{t.publisherCount}개 언론사 공통 보도</span></div><ChevronRight size={15}/></button>):<div className="ranking-empty"><div className="chart-icon"><i/><i/><i/><span>↗</span></div><strong>오늘의 흐름이 모이는 곳</strong><p>언론사를 선택하면<br/>공통 이슈를 순위로 보여드려요.</p></div>}<button className="method-link" onClick={()=>setMethod(true)}><Info size={14}/> 이슈 랭킹은 어떻게 만들어지나요? <ChevronRight size={14}/></button></section>
 <section className="scrap-panel"><div className="scrap-symbol"><Bookmark size={21}/></div><h2>읽고, 남기고, 다시 생각하기.</h2><p>기억하고 싶은 기사는 스크랩으로.<br/>당신만의 뉴스 아카이브를 만들어보세요.</p><button onClick={()=>{setView('scraps');setFilter('all')}}>내 스크랩 보기 <ArrowRight size={16}/></button></section><div className="editor-note"><span>THE PRESSROOM NOTE</span><p>하나의 사건, 여러 개의 시선.<br/>뉴스를 비교하면 맥락이 보입니다.</p><div/></div></aside></div>
 </main><footer><div><a className="footer-brand" href="/">PRESSROOM<span>■</span></a><span>다양한 시선이 만나는 나의 뉴스 데스크</span></div><p>기사 제목과 원문 링크를 제공합니다. 모든 기사 저작권은 해당 언론사에 있습니다.</p><span>© {new Date().getFullYear()} PRESSROOM</span></footer>
 <Dialog open={settings} onOpenChange={setSettings}><DialogContent className="press-dialog"><DialogTitle className="dialog-title">나의 언론사 선택<span>.</span></DialogTitle><DialogDescription>보고 싶은 언론사를 선택하세요. 선택한 언론사의 온라인 1면과 오피니언이 뉴스 데스크에 나타납니다.</DialogDescription><div className="selection-bar"><span>{draft.length}개 선택됨</span><button onClick={()=>setDraft(draft.length===publishers.length?[]:publishers.map(p=>p.id))}>{draft.length===publishers.length?'전체 해제':'전체 선택'}</button></div><div className="publisher-options">{publishers.map(p=><label className={'publisher-option '+(draft.includes(p.id)?'selected':'')} key={p.id}><span className="publisher-monogram" style={{color:p.color}}>{p.short}</span><span><strong>{p.name}</strong><small>{p.type}</small></span><Checkbox aria-label={p.name} checked={draft.includes(p.id)} onCheckedChange={checked=>setDraft(d=>checked?[...d,p.id]:d.filter(id=>id!==p.id))}/></label>)}</div><div className="selection-note"><Info size={15}/><span>1면은 언론사 홈페이지의 주요 기사입니다. 지면 PDF는 제공하지 않습니다.</span></div>{user?<button className="primary-button full-width" onClick={saveSettings} disabled={busy}>{busy?<LoaderCircle size={17} className="spin"/>:<Check size={17}/>} {draft.length}개 언론사로 데스크 저장</button>:<a href={signInUrl} target="_top" className="primary-button full-width">로그인 후 언론사 설정하기 <ArrowRight size={17}/></a>}</DialogContent></Dialog>
 <Dialog open={!!topic} onOpenChange={o=>!o&&setTopic(null)}><DialogContent className="press-dialog topic-dialog"><DialogTitle>{topic?.title}</DialogTitle><DialogDescription>{topic?.summary} · {topic?.publisherCount}개 언론사 공통 보도</DialogDescription>{topic?.articleIds.map(id=>state.articles.find(a=>a.id===id)).filter((a):a is Article=>!!a).map(a=><ArticleCard key={a.id} a={a}/>)}</DialogContent></Dialog>
 <Dialog open={method} onOpenChange={setMethod}><DialogContent className="press-dialog"><DialogTitle>이슈 랭킹의 기준</DialogTitle><DialogDescription>조회수가 아닌, 여러 언론사의 공통 보도를 기준으로 합니다.</DialogDescription><div className="method-body"><p><b>01 · 수집</b> 선택한 언론사의 온라인 1면과 오피니언에서 기사 제목·발행 정보·원문 링크를 수집합니다.</p><p><b>02 · 중복 정리</b> 같은 URL은 한 번만 저장합니다. GPT가 같은 사건을 다룬 기사들을 하나의 주제로 묶습니다.</p><p><b>03 · 순위</b> 최근 48시간 수집 기사 중 서로 다른 언론사 수가 많은 주제가 먼저 나타납니다. 동률이면 최근 기사를 우선합니다.</p><div className="selection-note">{state.aiAvailable?'GPT 연결이 설정되어 있습니다. 분석에 실패하면 키워드 방식으로 전환하고 표시합니다.':'GPT 연결 전에는 제목 유사도 기반 키워드 분석을 사용합니다. GPT 분석에는 서버의 OpenAI API 키 설정이 필요합니다.'}</div><p className="meta-caption">자동 분류에는 오류가 있을 수 있습니다. 각 순위에서 관련 원문을 함께 확인하세요.</p></div></DialogContent></Dialog>
 </div>
}
